#If a PR is labeled as 'type: deployment', automatically add reviewers as appropriate for each environment.
# Assignments can be configured on a per environment basis with the configuration stored in (.github/auto-assign)

#To add a new environment:
#  1. Add the name to the `jobs.add-reviewers.strategy.matrix.environment` array
#  2. Create a new configuration in (.github/auto-assign/<environment>)

name: "Auto Assign Reviewers"
on:
  pull_request:
    #The Labeler Workflow adds with a label 'type: deployment', which triggers this workflow
    types: [labeled]

jobs:
  get-environments:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-environments-matrix.outputs.environments }}
    steps:
      - id: set-environments-matrix
        #Eventually, we should pull the environment json list from the cicd endpoint
        run: echo "::set-output name=environments::{\"environments\":[sandbox, staging, \"staging-ie\", production, \"production-ie\""]}"

  add-reviewers:
    needs: set-environment-matrix
    runs-on: ubuntu-latest
    if: "contains(github.event.pull_request.labels.*.name, 'type: deployment')"
    strategy:
      matrix: ${{fromJSON(needs.get-environments.outputs.matrix)}}
      fail-fast: false
    steps:
      - name: Debug
        if: ${{ env.ACTIONS_STEP_DEBUG == true }}
        run: "core.debug(`Pull Request Event: ${github.event.pull_request}`);"

      - name: Add reviewers for ${{ matrix.environment }} deployments
        if: "${{ github.event.label.name == 'environment: ${{ matrix.environment }}' }}"
        uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: ".github/auto-assign/${{ matrix.environment }}.yml"
      - name: Mark the PR as ready
        if: success() && github.event.pull_request.draft == true
        run: gh pr ready

      - name: Add default reviewers if no environment label is found
        if: "!contains(github.event.pull_request.labels.*.name, 'environment')"
        id: add-default-reviewers
        uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: ".github/auto-assign/default.yml"
